### ISSUE TITLE
[1.7.10] [Cauldron] Error Patching ChunkProviderServer

### ISSUE THREAD

**Issue by Katelyn-SN** [nallar/nTweaks#3]
```
[17:39:04 ERROR]: Could not pass event PlayerInteractEntityEvent to GriefPrevention v10.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1545) [nh.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
```

**Comment by tf101-wizard** [comment]
Previous issue was solved after compiling against a newer forge, I still have this issue however i thought it was GriefPreventions issue with holding world objects @nallar but that does not seem to be the case. It also causes a few more errors of similar type which do not include anything paste the 

```
Caused by: java.lang.NullPointerException
```

**Comment by tf101-wizard** [comment]
This error was kind enough to include something after the null pointer

```
[17:16:08] [Server thread/ERROR]: Could not pass event BlockFromToEvent to GriefPrevention v10.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.block.BlockDynamicLiquid.func_149674_a(BlockDynamicLiquid.java:195) [akr.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:740) [mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:272) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.getUID(CraftWorld.java:547) ~[CraftWorld.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.equals(CraftWorld.java:1234) ~[CraftWorld.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940) ~[?:1.8.0_25]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.claimsEnabledForWorld(GriefPrevention.java:2423) ~[?:?]
	at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockFromTo(BlockEventHandler.java:596) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	... 11 more
```

**Comment by nallar** [comment]
GriefPrevention is storing unloaded worlds in maps.

I've fixed this before, apply these changes to the current version of GriefPrevention: https://github.com/nallar/GriefPrevention/commit/2aafe1974e422e15353a104463fa6dfa520f6cb3

About the issue patching, not sure, presumably cauldron-related and it might not matter.

**Comment by tf101-wizard** [comment]
I don't even know where to begin with the new GreifPrevention most  of the structure for that has changed and they do seem to be using world.getName() lots.

**Comment by tf101-wizard** [comment]
Alright I've applied those changes to it few things were moved around and renamed but that was about it now to see if it fixes the problem.

**Comment by tf101-wizard** [comment]
Yes that seems to have fixed the issue. As for the patch its actually erroring i pulled that patch as it actually is causing a crash mid way through start-up when loading the worlds.

You may not realize it but nTweaks makes a serious difference we went from around 2000+ Entities down to around 600 when about 50 players are on with just around 6k in chunks loaded it really does help keep the TPS lag down from all the entities processing their AIs

**Comment by tf101-wizard** [comment]
Actually seems we do have quite the issue not a single hostile is spawning anywhere.

**Comment by nallar** [comment]
To be honest I wouldn't recommend using NTweaks.

It's never been tested with Cauldron, and while it should work without it it's rather feature incomplete and it's unlikely I'll be working on it at all.

**Comment by tf101-wizard** [comment]
Kinda sad actually without breaking mods you should be able to make pretty
basic tweaks that servers could really benefit from. The spawning algorithm
itself seems to spawn slower and more stable as I don't see mob counts
jumping all over the place.

**Comment by tf101-wizard** [comment]
@nallar Mind taking a look at the mobspawning code and why they don't spawn in the nether?

We think its something to do with line 160

**Comment by nallar** [comment]
Hostiles are spawning in non-nether worlds then? You're probably right.

With TT I had fast spawning off for nether entirely due to issues, tried to fix it when making nTweaks but looks like I didn't manage to :P

**Comment by tf101-wizard** [comment]
Well i was really looking forward to Async chunk loading to be honest but after watching the recent attempts of another developer to replicate TT in 1.7 i can see the challenges in that.

**Comment by tf101-wizard** [comment]
@nallar May i ask for some clearer documentation on the variables in the MobSpawner class as i'd like to use this spawner if i can but at this moment in time even at night in the main world there are little to none of hostiles.

**Comment by Shybella** [comment]
Nerco here but the issue with entities on 1.7.10 has nothing to do with the amount or the spawning.(http://prntscr.com/6x6wgz)(40) online. 

Check your activation settings, the mobs navigate to track the players is extremely intensive. I wrote a fix to stop this from happening but Clearlagg allows you to change those settings. Also, stopping the activation few sections are a fresh spawn reduces load extremely. 

Honestly, making spawning depend on light levels will break several mods. This is a bad approach. Why not default a better nms for this?

Hope this helps!

**Comment by tf101-wizard** [comment]
You mind sharing your fixes as of right now to make our servers even
livable with 40 players online we have to disable entity ticking altogether
as it can be far past 200ms

**Comment by Shybella** [comment]
Grab Clearlagg and agjust the mob-range down to 3 example

mob-range:
  enabled: true
  zombie: 4
  skeleton: 4
  creeper: 4
  sheep: 4
  pig: 4
  cow: 4
  blaze: 4
  villager: 4
  enderman: 4
  witch: 4

then in your cauldron config set 

entity-bounding-box-max-size: 0

**Comment by nallar** [comment]
I've added a config file which makes it possible to disable the dontLoadSpawnChunks tweak, which is incompatible with MCPC. It is in Config/NTweaks.cfg.

**Comment by Katelyn-SN** [comment]
Well @nallar MCPC is a little bit of old news by now considering Cauldron now called KCauldron is pretty much getting daily updates :P

**Comment by nallar** [comment]
@Shybella 
The scaling of mob caps at night time isn't for performance reasons - it's to fix the issue where if you don't move around (staying in your base for example) mobs can spawn underground, fill up the caves and then when it comes to night time barely any mobs spawn as you're already at the cap. IMO it also makes sense to scale hostile mob caps up at night as there's a much larger area available for spawning.

@Katelyn-SN 

Implemented config option for mob spawning multiplier (set it to 999 and crash :D) in dad06709bd7cdd1. Only months late... guess you're not interested in debugging at this point. Try setting it higher to something like 2, are mob spawns closer to normal at night time?

**Comment by Katelyn-SN** [comment]
@nallar If it helps keep entities from using 3/4 of a server tick i don't see why i wouldn't help by debugging.
